---
- hosts: localhost
  connection: local

  vars:
    brews:
      - ansible
      - bash
      - fish
      - htop
      - reattach-to-user-namespace
      - tmux
      - neovim/neovim/neovim

    casks:
      - karabiner-elements

    fonts:
      - source-code-pro
      - source-sans-pro
      - source-serif-pro

  tasks:
    - name: install brews
      homebrew:
        name={{ item }}
        state=present
      with_items: "{{ brews }}"

    - name: install casks
      homebrew_cask:
        name={{ item }}
        state=present
      with_items: "{{ casks }}"

    - name: create KeyBindings directory
      file:
        path=~/Library/KeyBindings
        state=directory
        mode=0755

    - name: install DefaultKeyBinding.dict
      copy:
        src=DefaultKeyBinding.dict
        dest=~/Library/KeyBindings/DefaultKeyBinding.dict

    - name: install fonts
      synchronize:
        src=fonts/{{ item }}/OTF/
        dest=~/Library/Fonts/
      with_items: "{{ fonts }}"

    - name: install terminfos
      command: "tic {{ item }}"
      with_fileglob: "terminfos/*"
