---
- hosts: localhost
  connection: local

  vars:
    taps:
      - homebrew/dupes
      - neovim/neovim

    brews:
      - ansible
      - bash
      - fish
      - git
      - htop
      - ipcalc
      - mypy
      - picocom
      - python
      - python3
      - reattach-to-user-namespace
      - tmux
      - xz
      - youtube-dl
      - neovim/neovim/neovim

    casks:
      - keybase
      - visual-studio-code

    fonts:
      - source-code-pro
      - source-sans-pro
      - source-serif-pro

  tasks:
    - name: tap brew taps
      homebrew_tap:
        name={{ item }}
        state=present
      with_items: "{{ taps }}"

    - name: install brews
      homebrew:
        name={{ item }}
        state=present
      with_items: "{{ brews }}"

    - name: install casks
      homebrew_cask:
        name={{ item }}
        state=present
      with_items: "{{ casks }}"

    - name: create KeyBindings directory
      file:
        path=~/Library/KeyBindings
        state=directory
        mode=0755

    - name: install DefaultKeyBinding.dict
      copy:
        src=DefaultKeyBinding.dict
        dest=~/Library/KeyBindings/DefaultKeyBinding.dict

    - name: install tmux LaunchAgent
      template:
        src=io.rahulg.tmux.scratch.plist
        dest=~/Library/LaunchAgents/io.rahulg.tmux.scratch.plist

    - name: install fonts
      synchronize:
        src=fonts/{{ item }}/OTF/
        dest=~/Library/Fonts/
      with_items: "{{ fonts }}"

    - name: install terminfos
      command: "tic {{ item }}"
      with_fileglob: "terminfos/*"
