---
- hosts: localhost
  connection: local

  vars:
    taps:
      - homebrew/dupes
      - neovim/neovim
      - rahulg/hyv

    brews:
      - ansible
      - bash
      - clang-format
      - fish
      - flake8
      - git
      - guile
      - rahulg/hyv/hyv
      - ipcalc
      - lua
      - mtr
      - neovim/neovim/neovim
      - nmap
      - node
      - opensc
      - homebrew/dupes/openssh
      - picocom
      - pngnq
      - pwgen
      - python
      - python3
      - racket
      - ruby
      - rust
      - the_platinum_searcher
      - tmux
      - youtube-dl

    casks:
      - mjolnir
      - xquartz

    rocks:
      - mjolnir.hotkey
      - mjolnir.application
      - mjolnir.fnutils
      - mjolnir.geometry
      - mjolnir.screen
      - mjolnir.keycodes

    fonts:
      - source-code-pro
      - source-sans-pro
      - source-serif-pro


  tasks:
    - name: tap brew taps
      homebrew_tap:
        name={{ item }}
        state=present
      with_items: "{{ taps }}"

    - name: update brew indices
      homebrew:
        update_homebrew=yes

    - name: install brews
      homebrew:
        name={{ item }}
        state=present
      with_items: "{{ brews }}"

    - name: install reattach-to-user-namespace
      homebrew:
        name=reattach-to-user-namespace
        state=present
        options=with-wrap-launchctl,with-wrap-pbcopy-and-pbpaste

    - name: install casks
      homebrew_cask:
        name={{ item }}
        state=present
      with_items: "{{ casks }}"

    - name: install rocks
      luarocks:
        name={{ item }}
        state=present
        server=http://rocks.moonscript.org
      with_items: "{{ rocks }}"
      become: True
      become_user: root

    - name: create mjolnir config directory
      file:
        path=~/.mjolnir
        state=directory
        mode=0755

    - name: install mjolnir config
      copy:
        src={{ item }}
        dest=~/.mjolnir/
      with_fileglob: "mjolnir/*"

    - name: create KeyBindings directory
      file:
        path=~/Library/KeyBindings
        state=directory
        mode=0755

    - name: install DefaultKeyBinding.dict
      copy:
        src=DefaultKeyBinding.dict
        dest=~/Library/KeyBindings/DefaultKeyBinding.dict

    - name: install tmux LaunchAgent
      template:
        src=io.rahulg.tmux.scratch.plist
        dest=~/Library/LaunchAgents/io.rahulg.tmux.scratch.plist

    - name: install fonts
      synchronize:
        src=fonts/{{ item }}/OTF/
        dest=~/Library/Fonts/
      with_items: "{{ fonts }}"

    - name: install terminfos
      command: "tic {{ item }}"
      with_fileglob: "terminfos/*"
